[package]
name = "jj-cli"
version = "0.7.0"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2021"
rust-version = "1.64"  # Remember to update CI, contributing.md, and flake.nix
license = "Apache-2.0"
description = "Jujutsu (an experimental VCS)"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://docs.rs/jj-cli"
readme = "README.md"
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]
categories = ["command-line-utilities", "development-tools"]
default-run = "jj"

[[bin]]
name = "jj"
path = "src/main.rs"

[[bin]]
name = "fake-editor"
path = "testing/fake-editor.rs"

[[bin]]
name = "fake-diff-editor"
path = "testing/fake-diff-editor.rs"

[workspace]
members = ["lib", "lib/testutils", "lib/gen-protos"]

[build-dependencies]
cargo_metadata = "0.15.4"

[dependencies]
chrono = { version = "0.4.26", default-features = false, features = ["std", "clock"] }
clap = { version = "4.3.11", features = ["derive", "deprecated"] }
clap_complete = "4.3.2"
clap_mangen = "0.2.10"
config = { version = "0.13.3", default-features = false, features = ["toml"] }
criterion = {version = "0.5.1", optional = true }
crossterm = { version = "0.26", default-features = false }
dirs = "5.0.1"
esl01-renderdag = "0.3.0"
git2 = "0.17.2"
glob = "0.3.1"
hex = "0.4.3"
indexmap = "2.0.0"
itertools = "0.11.0"
jj-lib = { version = "=0.7.0", path = "lib", default-features = false }
maplit = "1.0.2"
once_cell = "1.18.0"
pest = "2.7.0"
pest_derive = "2.7.0"
regex = "1.9.1"
rpassword = "7.2.0"
serde = { version = "1.0", features = ["derive"] }
slab = "0.4.8"
tempfile = "3.6.0"
textwrap = "0.16.0"
thiserror = "1.0.43"
timeago = { version = "0.4.1", default-features = false }
toml_edit = { version = "0.19.12", features = ["serde"] }
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = { version = "0.3.17", default-features = false, features = ["std", "ansi", "env-filter", "fmt"] }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2.147" }

[dev-dependencies]
assert_cmd = "2.0.8"
assert_matches = "1.5.0"
insta = { version = "1.30.0", features = ["filters"] }
testutils = { path = "lib/testutils" }

[features]
default = []
bench = ["criterion"]
packaging = ["watchman"]
vendored-openssl = ["git2/vendored-openssl", "jj-lib/vendored-openssl"]
watchman = ["jj-lib/watchman"]

# It's often really useful to profile and run benchmarks on jj in --release
# mode, at the expense of some peak performance; so bump codegen-units to a
# high explicit number, and enable incremental builds to speed things up when
# iterating on patches
[profile.release]
incremental = true # normally off in --release mode
codegen-units = 16 # normally 256 when incremental=true; tone it down a bit...
debug = true
strip = "none"

# But when we cook a release for users to eat at the table, we should be more
# sophisticated: strip debug info (leaving symbols), codegen-units=1 to improve
# performance and binary size even further, and turn off incremental builds
# since they aren't needed.
[profile.cooked-release]
# Inherit from the "release" profile, as there may be other release defaults
# we haven't tweaked ourselves; inheriting them properly is good form.
inherits = "release"
incremental = false
codegen-units = 1 # see issue #1833 for details
strip = "debuginfo"
